id: IAB5ADFBE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:40:54+00:00'
last_modified: '2022-06-16T05:36:29.974492+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19901
  title: མཉེན་ཆས་མ་ལག་རྩིས་འཕྲུལ་ཁོག་ཏུ་འཇོག་ལུགས་དང་པོའི་ལས་ཅན་འཇུག་པའི་སྒོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2894':
      image_group_id: I2PD20730
      title: Volume 1 of mnyen chas ma lag rtsis 'phrul khog tu 'jog lugs dang po'i
        las can 'jug pa'i sgo/
      total_pages: 44
      order: 1
      base_file: 2894.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
